pixel_to_base_mapper_node:
  ros__parameters:
    output_frame_id: "camera_color_optical_frame"

    camera_info_topic: "/camera/camera/color/camera_info"
    color_image_topic: "/camera/camera/color/image_raw"
    depth_image_topic: "/camera/camera/aligned_depth_to_color/image_raw"

    wood_detection_topic: "/vision/wood_detection"
    box_detection_topic: "/vision/box_detection"

    wood_objects_topic: "/vision/wood_objects"
    box_objects_topic: "/vision/box_objects"

    default_box_size_x_m: 0.08
    default_box_size_y_m: 0.08
    default_box_size_z_m: 0.05

    fake_depth_m: 0.55
    use_fake_depth_if_missing: false

    overlay_timeout_sec: 1.0
    stale_timeout_sec: 2.0
