vision_detection_marker_node:
  ros__parameters:
    marker_frame_id: "camera_color_optical_frame"
    marker_publish_rate_hz: 5.0

    wood_marker_size_x_m: 0.04
    wood_marker_size_y_m: 0.04
    wood_marker_size_z_m: 0.04

    box_marker_size_x_m: 0.08
    box_marker_size_y_m: 0.08
    box_marker_size_z_m: 0.05

    wood_detection_timeout_sec: 1.0
    wood_confidence_threshold: 0.5
