yolo_detect_node:
  ros__parameters:
    image_topic: "/camera/camera/color/image_raw"
    camera_info_topic: "/camera/camera/color/camera_info"
    annotated_image_topic: "/vision/yolo/image_annotated"
    detections_topic: "/vision/yolo/detections_json"
    model_path: "/home/asus/ros_vision/src/robot_vision_pipeline/models/yolov8.pt"
    device: "cpu"
    conf_threshold: 0.35
    iou_threshold: 0.45
    imgsz: 256
    max_det: 20
    detect_period_sec: 0.0
    show_gui: false
    publish_annotated: true
    image_qos: "reliable"
    class_filter: "wood,box"
    verbose_log: false
    enable_roi_crop: true
    roi_x: 100
    roi_y: 80
    roi_width: 440
    roi_height: 320
    publish_roi_debug_image: true
