yolo_json_to_box_detection_node:
  ros__parameters:
    detections_json_topic: "/vision/yolo/detections_json"
    depth_topic: "/camera/camera/aligned_depth_to_color/image_raw"
    depth_roi_half_size: 5
    fake_depth_m: 0.55
    use_fake_depth: false
