#!/usr/bin/env python3
"""Entry point for ``ros2 run gp7_vision_pipeline pixel_to_base_mapper_node``."""

import sys

from gp7_vision_pipeline.pixel_to_base_mapper_node import main

if __name__ == "__main__":
    main(sys.argv)
